name: Docker Compose Actions Workflow
on: push
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Build the stack
      #  run: docker-compose up -d
      - name: Startup the container
        #run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus
        run: docker-compose up -d
      - name: Trust PSGallery
        shell: pwsh
        run: Set-PSRepository PSGallery -InstallationPolicy Trusted
      - name: Install PSFramework
        shell: pwsh
        run: Install-Module PSFramework, PoshRSJob -ErrorAction Stop
      - name: Perform the import of acastools
        shell: pwsh
        run: Import-Module ./acastools.psd1 -ErrorAction Stop
      - name: Test the port and accept self-signed cert
        run: curl -s --retry 10 --retry-connrefused https://localhost:8834/ --insecure
