name: Docker Compose Actions Workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest
      - name: Install dependencies, import the module
        #/home/runner/.local/share/powershell/Modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, PoshRSJob -ErrorAction Stop
          Import-Module ./acastools.psd1 -ErrorAction Stop
      - name: Test the port and accept self-signed cert
        run: curl -s --retry 20 --retry-connrefused https://localhost:8834/ --insecure
      - name: Write license
        run: 'echo "$NLICENSE" > nessus.license'
        shell: bash
        env:
          NLICENSE: ${{secrets.LICENSE}}
      - name: Execute commands inside container
        run: |
          ls -la
          pwd
          docker cp nessus.license nessus:/tmp
          docker cp setup-nessus.sh nessus:/tmp
          docker exec nessus bash -c 'chmod +x /tmp/setup-nessus.sh'
          docker exec nessus bash -c 'ls -la /tmp'
          docker exec nessus bash -c '/tmp/setup-nessus.sh'
