name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Build the stack
      #  run: docker-compose up -d
      - name: Startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus
      - name: Sleep for a bit so that it has time to start
        run: sleep 10
      - name: Test the port
        run: curl -s --retry 10 --retry-connrefused http://localhost:8834/
      - name: Trust PSGallery
        shell: pwsh
        run: Set-PSRepository PSGallery -InstallationPolicy Trusted
      - name: Install PSFramework
        shell: pwsh
        run: Install-Module PSFramework -ErrorAction Stop
      - name: Perform the import of acastools
        shell: pwsh
        run: Import-Module ./acastools.psd1 -ErrorAction Stop