name: Docker Compose Actions Workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest
      #- name: Install dependencies, import the module
      #  shell: pwsh
      #  run: |
      #    Set-PSRepository PSGallery -InstallationPolicy Trusted
      #    Install-Module PSFramework, PoshRSJob -ErrorAction Stop
      #    Import-Module ./acastools.psd1 -ErrorAction Stop
      - name: Test the port and accept self-signed cert
        run: curl -s --retry 20 --retry-connrefused https://localhost:8834/ --insecure
      - name: Execute commands inside container
        run: |
          ls -la
          pwd
          docker cp setup-nessus.sh nessus:/tmp
          #echo  ${{ secrets.LICENSE }} >> /tmp/nessus.license
          #docker cp /tmp/nessus.license nessus:/tmp
          #docker exec nessus bash -c 'chmod +x /tmp/setup-nessus.sh'
          docker exec nessus bash -c 'ls -la /tmp'
          #docker exec nessus bash -c '/tmp/setup-nessus.sh'
