name: Actions Workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache PowerShell modules
        id: cache-psmodules
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.local/share/powershell/Modules/PSFramework
            /home/runner/.local/share/powershell/Modules/PoshRSJob
          key: ${{ runner.os }}-psmodules
      - name: Download and startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest
      - name: Install PowerShell dependencies
        if: steps.cache-psmodules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, PoshRSJob -ErrorAction Stop
      - name: Write nessus license
        run: 'echo "$NLICENSE" > /tmp/nessus.license'
        shell: bash
        env:
          NLICENSE: ${{secrets.LICENSE}}
      - name: Execute commands inside container
        run: |
          docker cp /usr/bin/expect nessus:/usr/bin
          docker cp /tmp/nessus.license nessus:/tmp
          docker cp setup-nessus.sh nessus:/tmp
          docker exec nessus bash -c 'chmod +x /tmp/setup-nessus.sh'
          docker exec nessus bash -c '/tmp/setup-nessus.sh'
      - name: Import acastools
        shell: pwsh
        run: Import-Module ./acastools.psd1
      - name: Sleep if cache used to give nessus time to startup
        if: steps.cache-psmodules.outputs.cache-hit == 'true'
        run: sleep 3
      - name: Test the port and accept self-signed cert
        run: curl -s --retry 10 --retry-connrefused https://localhost:8834/ --insecure
